CREATE TABLE users (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_name TEXT NOT NULL UNIQUE,
  full_name TEXT NOT NULL,
  password TEXT NOT NULL,
  date_created TIMESTAMP DEFAULT now() NOT NULL,
  date_modified TIMESTAMP
);
CREATE TYPE category AS ENUM ('original', 'edited', 'approved');
CREATE TABLE substitutions (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  substitution_string TEXT NOT NULL,
  user_id INTEGER
        REFERENCES users(id) ON DELETE CASCADE NOT NULL
);
CREATE TABLE docs (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  text TEXT NOT NULL,
  current_category category NOT NULL,
  creator_id INTEGER
        REFERENCES users(id) ON DELETE CASCADE NOT NULL,
  editor_id INTEGER
        REFERENCES users(id) ON DELETE CASCADE,
  judge_id INTEGER
        REFERENCES users(id) ON DELETE CASCADE,
  substitution_id INTEGER
        REFERENCES substitutions(id) ON DELETE CASCADE
);